// ================================================= Stockage des data =================================================
var data = [
  {
    analogies: "un Guerrier",
    valeurAnalogies: "Myamoto Musashi",
    text: "<b>Miyamoto Musashi</b> de son vrai nom <b>Shinmen Bennosuke</b> est un guerrier ayant vécu pendant l’époque du shogunat d’Edo. Ce personnage entra dans la légende nippone grâce à un record qui n’a jamais été battu, celui de plus de <b>60 duels gagnés</b> lors de sa vie. Mais il était plus qu’un guerrier, il excellait dans les différentes formes d’<b>arts</b> ainsi que dans <b>l’enseignement</b> et dans la rédaction de plusieurs <b>ouvrages d’arts martiaux</b> célèbres.<br><br>Pour moi il est un exemple de polyvalence, d’honneur et de persévérance qui m’inspire dans mon quotidien et m’aide à garder une certaine rigueur dans mon travail.",
    illustration: "IMG/guerrier.jpg",
    imgFond: "IMG/FondGuerrier.png",
    id: "section1",
  },
  {
    analogies: "un Plat",
    valeurAnalogies: "le Phô",
    text: "Le <b>phở</b> est une recette traditionnelle de cuisine vietnamienne, à base de bouillon de viande et de nouilles de riz, agrémentés de divers ingrédients. Le nom phở viendrait probablement du mot français <b>pot-au-feu</b> en rapport avec l'époque de l'Indochine. Ce plat national <b>emblématique</b> du Vietnam par lequel débute toute journée, peut se consommer à tout moment de la journée, il est souvent synonyme de <b>convivialité</b> et de moment en <b>famille</b>.<br><br>Étant l’un de mes plats d’enfance préférés et me rappelant de bons souvenirs familiaux, je pense que le phở est le plat qui me correspond le mieux.",
    illustration: "IMG/phe.jpg",
    imgFond: "IMG/FondPho.png",
    id: "section2",
  },
  {
    analogies: "un Lieu",
    valeurAnalogies: "La Baie de Ha Long",
    text: "En vietnamien, Ha long signifie « <b>descente du dragon</b> ». L’une de ces légendes raconte que la baie serait née des battements de queue d’un dragon géant descendu dans la mer pour domestiquer les courants marins. Il aurait entaillé les montagnes pour former ce paysage unique. Son panorama marin naturel préservé spectaculaire et exceptionnel de <b>1 969 îles</b> calcaires immergées, et la richesse biologique de son écosystème tropical lui valent d'être inscrite sur la liste du Patrimoine mondial de <b>l'UNESCO</b>. <br><br>Son paysage paradisiaque et apaisant ainsi que son histoire et ses légendes font que je porte un intérêt spécial envers ce lieu.",
    illustration: "IMG/lac.jpg",
    imgFond: "IMG/FondLieu.png",
    id: "section3",
  },
  {
    analogies: "un Film",
    valeurAnalogies: "Akira",
    text: "Ce <b>chef-d’œuvre</b> d’animation est un pilier du cyberpunk et de la dystopie. Celui-ci nous emmène dans un futur proche ou la ville de <b>Tokyo</b> est devenue une mégalopole rongée par la <b>corruption</b> et la <b>pauvreté</b>. Nous y suivrons les aventures d’Akira et de Tetsuo, les deux personnages principaux dans cette ville manipulée par l’armée et les dirigeants politiques. <br><br>Ce film est pour moi et pour d’autres artistes une source d’inspiration dans sa direction artistique ainsi que dans ses choix scénaristiques, malgré le fait qu’il commence à dater il reste tout de même une référence dans le milieu.",
    illustration: "IMG/Akira.jpg",
    imgFond: "IMG/porte.png",
    id: "section4",
  },
  {
    analogies: "un Artiste",
    valeurAnalogies: "Daniel Arsham",
    text: "Daniel Arsham est un artiste américain, à travers ses différentes œuvres il essaie de représenter le <b>temps</b> qui s’écoule et les effets que celui-ci a sur l’environnement. Daniel Arsham a réalisé plusieurs collaborations comme avec l’artiste musical <b>Gunna</b> ou encore avec d’autres enseignes comme <b>Dior</b> ou <b>Pokémon</b>. Ce qui lui a permis d’exprimer son art de manière libre et d’acquérir une renommée mondiale. <br><br>Je porte une attention particulière à celui-ci, car de nos jours le temps est une notion précieuse que nous utilisons malheureusement trop souvent à mauvais escient.",
    illustration: "IMG/DA.jpg",
    imgFond: "IMG/FondDA.png",
    id: "section5",
  },
  {
    analogies: "une Exposition",
    valeurAnalogies: "Ikeuchi Tokyo",
    text: "Cette exposition est centrée sur des sculptures de style <b>Cyberpunk</b> et qui ont la particularité de pouvoir être portées. Ces sculptures sont donc exposées à la <b>Galerie Sai à Tokyo</b> et ont été réalisées par l’artiste « <b>Hiroto Ikeuchi</b> ». Celui-ci mêle plusieurs inspirations de la pop culture comme l’univers de Star Wars, les célèbres Gundams ou encore la série animée Zoids. <br><br>Cette exposition représente à la perfection mon envie de création ainsi que l’importance du choix des inspirations et des références que j’incorpore dans mon travail.",
    illustration: "IMG/EXPO.jpg",
    imgFond: "IMG/EXPOfond.png",
    id: "section6",
  },
  {
    analogies: "un Jeu Vidéo",
    valeurAnalogies: "Ghost Of Tsushima",
    text: "Ghost of Tsushima se déroule en <b>1274</b>. Il est basé sur des événements historiques comme l’<b>invasion</b> de l’île de Tsushima par les <b>Mongoles</b>. Lors de ce périple le joueur y incarnera un rōnin qui devra faire le choix entre garder ses valeurs de samurai ou y renoncer pour assouvir sa vengeance. Tout au long de celui-ci, le jeu arrive à garder une <b>cohérence historique</b> tout en posant les bases d'une histoire fictive. <br><br>Cela représente pour moi un idéal à atteindre, une maîtrise d’un sujet et d’une mise en scène que peu de gens parviennent à réussir.",
    illustration: "IMG/JV.png",
    imgFond: "IMG/JVfond.png",
    id: "section7",
  },
];
